### ISSUE TITLE
Missing comma in date

### ISSUE THREAD

**Issue by davidtranhq** [pidgey0403/Focus#2]
Contrary to the name of the application (e.g. Focus), the missing comma in the date is distracting.

## Expected Behaviour

Comma in the date between the day (e.g. Thursday) and the month (e.g. June):

e.g. Thursday, June 16, 2022

## Actual Behaviour

No comma in the date between the day (e.g. Thursday) and the month (e.g. June):

![image](https://user-images.githubusercontent.com/30242944/173989636-c1614c72-9540-418c-b2d3-81958af64db4.png)

## Suggested Fix

It may be possible to achieve this fix by adding a comma to the code that generates today's date. I'm not entirely sure though, maybe someone with more experience could take a look?

**Comment by pidgey0403** [comment]
Thanks @davidtranhq for your invaluable feedback. #1fixes this, so I'm closing this issue.

**Comment by pidgey0403** [comment]
Closed

**Comment by pidgey0403** [comment]
issue closed
